# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "efd8b1e16f05132acf6edcf2827eeab21e0e00db"
    hooks:
      - id: prettier
        types_or:
          - ts
          - tsx
