[workspace]
members = [
  "api",
  "chir-solver",
  "common",
  "fuqinho-solver",
  "hungarian-solver",
  "sandbox/hello",
  "sandbox/lifegame",
  "sandbox/lifegame-wasm",
  "oka-solver",
  "psh-solver",
  "psh-validator",
  "tanakh-solver",
  "wasm",
]
