CREATE TABLE `problems` (
    `id` INT PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE `solutions` (
    `uuid` CHAR(36) PRIMARY KEY,
    `problem_id` INT NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`problem_id`) REFERENCES `problems` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE `submissions` (
    `uuid` CHAR(36) PRIMARY KEY,
    `submission_id` TEXT NOT NULL,
    `state` ENUM('PROCESSING', 'FINISHED') NOT NULL,
    `accepted` BOOLEAN NOT NULL DEFAULT FALSE,
    `score` BIGINT DEFAULT 0,
    `error` TEXT NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`uuid`) REFERENCES `solutions` (`uuid`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE `evaluations` (
    `uuid` CHAR(36) PRIMARY KEY,
    `accepted` BOOLEAN NOT NULL,
    `score` BIGINT NOT NULL,
    `error` TEXT NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`uuid`) REFERENCES `solutions` (`uuid`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
