[package]
name = "psh-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
chrono = "*"
common = { path = "../common" }
euclid = "*"
lyon_geom = "*"
rand = "*"