name: Deploy frontend

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/462797584958/locations/global/workloadIdentityPools/github/providers/github
          service_account: icfpc2023-github@icfp-contest-compute.iam.gserviceaccount.com
      - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: asia-northeast1-docker.pkg.dev
          project_id: icfp-contest-compute/icfpc2023-frontend
          image_name: icfpc2023-frontend
          image_tag: ${{ github.sha }}
          dockerfile: ./frontend/Dockerfile
          context: .
