name: Deploy frontend

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/462797584958/locations/global/workloadIdentityPools/github/providers/github
          service_account: icfpc2023-github@icfp-contest-compute.iam.gserviceaccount.com

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./frontend/Dockerfile
          push: true
          tags: "asia-northeast1-docker.pkg.dev/icfp-contest-compute/icfpc2023-frontend/icfpc2023-frontend:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: icfpc2023-frontend
          image: "asia-northeast1-docker.pkg.dev/icfp-contest-compute/icfpc2023-frontend/icfpc2023-frontend:${{ github.sha }}"
          region: asia-northeast1
          project_id: "icfp-contest-compute"
